toro_cms:
    resource: "@ToroShopCmsBundle/Resources/config/route/main.yml"
    prefix: /

bitbag_sylius_cms_plugin_admin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/admin.yml"
    prefix: /

phpmob_sylius_settings_plugin_admin:
    resource: "@PhpMobSyliusSettingsPlugin/Resources/config/routing/admin.yml"
    prefix: /root

sylius_admin_toro_geo_filter:
    resource: "@ToroShopAddressBundle/Resources/config/route/sylius_admin.yml"
    prefix: /

sylius_admin_toro_geo_crud:
    resource: "@ToroShopAddressBundle/Resources/config/route/admin.yml"
    prefix: /root
