imports:
     - { resource: "@ToroShopCoreBundle/Resources/config/grid/main.yml" }
     - { resource: "./sylius_resource.yml" }
     - { resource: "./sylius_taxonomy.yml" }
     - { resource: "./state_machine/sylius_order.yml" }

     - { resource: "@ToroShopAddressBundle/Resources/config/app/config.yml" }
     - { resource: "@ToroShopAddressBundle/Resources/config/app/sylius_override.yml" }
     - { resource: "@ToroShopCurrencyBundle/Resources/config/app/config.yml" }
     - { resource: "@ToroShopCmsBundle/Resources/config/app/config.yml" }
     - { resource: '@BitBagSyliusCmsPlugin/Resources/config/config.yml' }
     - { resource: "@PhpMobSyliusSettingsPlugin/Resources/config/app/config.yml" }
